{
 "title": "UPS",
 "tags": [ "GC" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ip",
    "label": "IP",
    "query": {
     "query": "label_values(ups_input_voltage,ip)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ups_output_voltage{ip=\"$ip\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "ups_input_voltage{ip=\"$ip\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Input Frequency",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ups_input_frequency{ip=\"$ip\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Load",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ups_load{ip=\"$ip\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Battery charge level",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ups_battery_level{ip=\"$ip\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 13, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "ups_output_voltage{ip=\"$ip\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "ups_input_voltage{ip=\"$ip\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 11, "x": 13, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "expr": "ups_input_frequency{ip=\"$ip\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "ups_load{ip=\"$ip\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "ups_battery_voltage{ip=\"$ip\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  }
 ]
}